type Props={params:Promise<{slug:string}>};
const product={name:"کاپشن بمبر کلاسیک",code:"NB-WM-1001",price:"۱,۲۸۰,۰۰۰",moq:8};
export default async function ProductPage({params}:Props){const {slug}=await params;return <main dir="rtl">
  <div className="topbar"><div className="container topbar-inner"><span>فروش مستقیم از تولیدکننده</span><span>MOQ از ۸ عدد</span><span>ارسال سراسر کشور</span></div></div>
  <header className="site-header"><div className="container nav"><a href="/" className="brand">زمستان<span className="brand-sub">ZEMESTAN / WHOLESALE</span></a><nav className="navlinks"><a href="/">خانه</a><a href="/shop">فروشگاه</a><a href="/#collections">کالکشن</a><a href="/#wholesale">عمده‌فروشی</a></nav><div className="nav-actions"><a className="icon-btn" href="/shop">⌕</a><a className="btn" href="/shop">بازگشت</a></div></div></header>
  <section className="container product-layout">
    <div><div className="gallery-main"><div className="gallery-product" /></div><div className="gallery-thumbs"><div className="thumb">01</div><div className="thumb">02</div><div className="thumb">03</div><div className="thumb">04</div></div></div>
    <div className="product-info"><div className="kicker mono">PRODUCT / {slug}</div><h1>{product.name}</h1><p className="product-copy">فرم شهری و کاربردی برای کالکشن زمستانه فروشگاه‌های مردانه؛ طراحی شده برای خرید عمده با اطلاعات سفارش شفاف.</p><div className="price-box"><div className="wholesale-price">{product.price} تومان</div><small>قیمت عمده / هر عدد · قیمت‌گذاری بر اساس سفارش</small></div>
      <div className="variant-group"><div className="variant-label">رنگ</div><div className="swatches"><span className="swatch" style={{background:"#20221e"}}/><span className="swatch" style={{background:"#4b4940"}}/><span className="swatch" style={{background:"#5a4632"}}/></div></div>
      <div className="variant-group"><div className="variant-label">سایز</div><div className="sizes"><span className="size active">M</span><span className="size">L</span><span className="size">XL</span><span className="size">XXL</span></div></div>
      <div className="qty-box"><div><strong>تعداد سفارش</strong><div className="variant-label">حداقل {product.moq} عدد</div></div><div className="qty-controls"><button>-</button><strong>{product.moq}</strong><button>+</button></div></div>
      <button className="btn primary product-cta">افزودن {product.moq} عدد به سفارش عمده</button><a className="btn product-cta" href="#details">راهنمای سایز و مشخصات</a>
    </div>
  </section>
  <section id="details" className="container section"><div className="section-head"><div><div className="section-kicker">PRODUCT DETAILS</div><h2 className="section-title">مشخصات محصول</h2></div></div><div className="detail-grid"><div className="detail-cell"><strong>کد محصول</strong><span>{product.code}</span></div><div className="detail-cell"><strong>حداقل سفارش</strong><span>{product.moq} عدد</span></div><div className="detail-cell"><strong>جنس</strong><span>پارچه زمستانی با لایه داخلی گرم</span></div><div className="detail-cell"><strong>فیت</strong><span>Regular / شهری</span></div><div className="detail-cell"><strong>فصل</strong><span>پاییز / زمستان</span></div><div className="detail-cell"><strong>وضعیت</strong><span>موجود برای سفارش عمده</span></div></div></section>
  <footer className="section" style={{background:"#15150f",color:"#eeece4",paddingBottom:40}}><div className="container"><div className="brand">زمستان</div><p style={{color:"#aaa697"}}>پوشاک مردانه زمستانه / فروش عمده</p></div></footer>
  <nav className="mobile-nav"><a href="/">خانه</a><a href="/shop">فروشگاه</a><a href="/#collections">کالکشن</a><a href="/#wholesale">عمده</a></nav>
</main>}
