<?php get_header(); ?>
<main class="sole-shell" id="home">
<section class="sole-hero sole-reveal"><div class="sole-grain"></div><div><div class="sole-eyebrow">AUTUMN / WINTER 2026</div><h1>کفشی برای<br>حرکت <em>بعدی</em></h1><p>طراحی مینیمال، فرم دقیق و راحتی واقعی. مجموعه‌ای از کفش‌های روزمره و استایل شهری که برای حرکت ساخته شده‌اند.</p><div class="sole-cta"><a class="sole-btn sole-btn-dark" href="<?php echo esc_url(wc_get_page_permalink('shop')); ?>">مشاهده محصولات ←</a><a class="sole-btn sole-btn-light" href="#new">جدیدها</a></div></div><div class="sole-shoe-stage"><div class="sole-orbit"></div><div class="sole-floating-tag">NEW DROP · 01 / 06</div><svg class="sole-shoe-art" viewBox="0 0 620 360" xmlns="http://www.w3.org/2000/svg" aria-label="کفش"><defs><linearGradient id="soleg" x1="0" x2="1"><stop stop-color="#262626"/><stop offset="1" stop-color="#555"/></linearGradient></defs><path d="M88 235 C135 217 175 177 218 112 C240 78 271 68 302 90 L371 149 C409 181 455 188 518 205 L575 222 C604 231 613 252 593 269 C573 285 536 293 493 294 L147 294 C92 294 55 278 61 259 C65 248 74 241 88 235Z" fill="url(#soleg)"/><path d="M213 113 C241 83 270 75 302 96 L368 151 C334 173 295 183 247 175 L184 160Z" fill="#777" opacity=".55"/><path d="M95 252 C207 268 395 260 586 242 C606 250 605 267 585 278 C559 291 528 295 493 295 L145 295 C91 295 58 279 63 260Z" fill="#f1f0ec"/><path d="M278 123 L350 184 M257 134 L331 193 M235 145 L308 202" stroke="#ddd" stroke-width="8" stroke-linecap="round" opacity=".7"/></svg></div></section>
<div class="sole-ticker"><div class="sole-ticker-track">NEW SEASON · FREE RETURNS · PREMIUM MATERIALS · CITY ESSENTIALS · NEW SEASON · FREE RETURNS · PREMIUM MATERIALS · CITY ESSENTIALS</div></div>
<section class="sole-section sole-reveal" id="collections"><div class="sole-section-head"><div><div class="sole-eyebrow">EXPLORE</div><h2 class="sole-section-title">کالکشن‌ها</h2></div><span class="sole-section-sub">انتخاب کن و استایل خودت را بساز</span></div><div class="sole-categories"><a class="sole-cat" href="<?php echo esc_url(wc_get_page_permalink('shop')); ?>"><small>01</small><div class="sole-mini-shoe"></div><strong>روزمره</strong></a><a class="sole-cat" href="<?php echo esc_url(wc_get_page_permalink('shop')); ?>"><small>02</small><div class="sole-mini-shoe"></div><strong>اسپرت</strong></a><a class="sole-cat" href="<?php echo esc_url(wc_get_page_permalink('shop')); ?>"><small>03</small><div class="sole-mini-shoe"></div><strong>کژوال</strong></a><a class="sole-cat" href="<?php echo esc_url(wc_get_page_permalink('shop')); ?>"><small>04</small><div class="sole-mini-shoe"></div><strong>جدیدها</strong></a></div></section>
<section class="sole-section sole-reveal" id="new"><div class="sole-section-head"><div><div class="sole-eyebrow">CURATED FOR YOU</div><h2 class="sole-section-title">جدیدترین‌ها</h2></div><a class="sole-section-sub" href="<?php echo esc_url(wc_get_page_permalink('shop')); ?>">مشاهده همه ←</a></div><div class="sole-products"><?php $q=new WP_Query(array('post_type'=>'product','posts_per_page'=>4,'post_status'=>'publish')); if($q->have_posts()): while($q->have_posts()): $q->the_post(); global $product; ?><article class="sole-card"><a href="<?php the_permalink(); ?>"><div class="sole-card-media"><?php if(has_post_thumbnail()) the_post_thumbnail('woocommerce_thumbnail'); else echo '<div class="sole-mini-shoe"></div>'; ?></div></a><div class="sole-card-info"><h3><a href="<?php the_permalink(); ?>" style="text-decoration:none"><?php the_title(); ?></a></h3><div class="sole-meta"><span><?php echo wp_kses_post($product->get_price_html()); ?></span><span><?php echo esc_html($product->is_in_stock()?'موجود':'ناموجود'); ?></span></div></div></article><?php endwhile; wp_reset_postdata(); else: ?><div class="sole-card"><div class="sole-card-info"><h3>هنوز محصولی اضافه نشده</h3><p>از پنل WooCommerce اولین کفش را اضافه کنید.</p></div></div><?php endif; ?></div></section>
<section class="sole-banner sole-reveal"><div><div class="sole-eyebrow" style="color:#999">SOLE / LIMITED</div><h2>کمتر، اما<br>بهتر.</h2><p>قطعات محدود، متریال باکیفیت و طراحی‌ای که قرار نیست فصل بعد از مد بیفتد.</p><a class="sole-btn sole-btn-accent" href="<?php echo esc_url(wc_get_page_permalink('shop')); ?>">خرید کالکشن</a></div></section>
<section class="sole-section sole-reveal"><div class="sole-stats"><div class="sole-stat"><b>24h</b><span>ارسال سریع سفارش‌ها</span></div><div class="sole-stat"><b>30</b><span>روز ضمانت بازگشت</span></div><div class="sole-stat"><b>100%</b><span>تجربه خرید آنلاین امن</span></div></div></section>
</main>
<?php get_footer(); ?>
