<?php get_header(); ?>
<main id="home" class="shell">
<section class="hero reveal" aria-labelledby="hero-title"><div class="grain"></div><div class="hero-copy"><div class="eyebrow">SOLE / COLLECTION 2026</div><h1 id="hero-title">کفشی برای<br>حرکت <em>بعدی</em></h1><p>برای خرید کفش مردانه، از میان مدل‌های روزمره، اسپرت و رانینگ انتخاب کنید؛ با طراحی مینیمال، فرم کاربردی و تمرکز بر راحتی در استفاده روزانه.</p><div class="hero-cta"><a class="primary" href="<?php echo esc_url(function_exists('wc_get_page_permalink') ? wc_get_page_permalink('shop') : home_url('/')); ?>">مشاهده کفش‌ها ←</a><a class="secondary" href="#new">▶ معرفی کالکشن جدید</a></div></div><div class="shoe-stage" aria-hidden="true"><div class="orbit"></div><div class="floating-tag">NEW COLLECTION · 2026</div><div class="shoe"><svg viewBox="0 0 620 360" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><defs><linearGradient id="g" x1="0" x2="1"><stop stop-color="#262626"/><stop offset="1" stop-color="#555"/></linearGradient></defs><path d="M88 235 C135 217 175 177 218 112 C240 78 271 68 302 90 L371 149 C409 181 455 188 518 205 L575 222 C604 231 613 252 593 269 C573 285 536 293 493 294 L147 294 C92 294 55 278 61 259 C65 248 74 241 88 235Z" fill="url(#g)"/><path d="M213 113 C241 83 270 75 302 96 L368 151 C334 173 295 183 247 175 L184 160Z" fill="#777" opacity=".55"/><path d="M95 252 C207 268 395 260 586 242 C606 250 605 267 585 278 C559 291 528 295 493 295 L145 295 C91 295 58 279 63 260Z" fill="#f1f0ec"/><path d="M278 123 L350 184 M257 134 L331 193 M235 145 L308 202" stroke="#ddd" stroke-width="8" stroke-linecap="round" opacity=".7"/><circle cx="450" cy="235" r="13" fill="#222"/><path d="M460 236 L560 245" stroke="#111" stroke-width="5" opacity=".5"/></svg></div></div></section>
<div class="ticker" aria-label="ویژگی‌های فروشگاه"><div class="ticker-track">DESIGNED FOR EVERYDAY MOTION ✦ NEW COLLECTION ✦ PREMIUM MATERIALS ✦ COMFORT FIRST ✦ DESIGNED FOR EVERYDAY MOTION ✦ NEW COLLECTION ✦ PREMIUM MATERIALS ✦ COMFORT FIRST ✦</div></div>
<section id="collections" class="section reveal" aria-labelledby="collections-title"><div class="section-head"><div><div class="eyebrow">Explore</div><h2 id="collections-title" class="section-title">خرید کفش بر اساس سبک</h2></div><div class="section-sub">سبک مناسب خودت را انتخاب کن ←</div></div><div class="categories"><a class="cat" href="<?php echo esc_url(function_exists('wc_get_page_permalink') ? wc_get_page_permalink('shop') : home_url('/')); ?>"><small>01</small><div class="mini-shoe" aria-hidden="true"></div><strong>کفش روزمره</strong><span>برای استفاده روزانه و استایل شهری</span></a><a class="cat" href="<?php echo esc_url(function_exists('wc_get_page_permalink') ? wc_get_page_permalink('shop') : home_url('/')); ?>"><small>02</small><div class="mini-shoe" aria-hidden="true"></div><strong>کفش رانینگ</strong><span>سبک و مناسب فعالیت و حرکت</span></a><a class="cat" href="<?php echo esc_url(function_exists('wc_get_page_permalink') ? wc_get_page_permalink('shop') : home_url('/')); ?>"><small>03</small><div class="mini-shoe" aria-hidden="true"></div><strong>کفش اسپرت</strong><span>ترکیب راحتی با ظاهر امروزی</span></a><a class="cat" href="<?php echo esc_url(function_exists('wc_get_page_permalink') ? wc_get_page_permalink('shop') : home_url('/')); ?>"><small>04</small><div class="mini-shoe" aria-hidden="true"></div><strong>کفش لوکس</strong><span>جزئیات دقیق برای استایل متفاوت</span></a></div></section>
<section id="shop" class="section reveal" aria-labelledby="products-title"><div class="section-head"><div><div class="eyebrow">Selected collection</div><h2 id="products-title" class="section-title">محبوب‌ترین مدل‌های کفش</h2></div><a class="secondary" href="<?php echo esc_url(function_exists('wc_get_page_permalink') ? wc_get_page_permalink('shop') : home_url('/')); ?>">مشاهده همه محصولات ←</a></div><div class="products">
<article class="product"><div class="product-media"><span class="badge">جدید</span><button class="heart" type="button" onclick="toggleHeart(this)" aria-label="افزودن Mono Runner به علاقه‌مندی‌ها">♡</button><div class="p-shoe" aria-hidden="true"><div class="p-upper"></div><div class="p-laces"></div><div class="p-sole"></div></div></div><div class="product-info"><h3>Mono Runner / Black</h3><div class="meta"><span>کفش رانینگ مردانه</span><span class="price">۳,۸۹۰,۰۰۰ تومان</span></div></div><a class="primary" style="display:block;text-align:center;width:100%;margin-top:12px" href="<?php echo esc_url(function_exists('wc_get_page_permalink') ? wc_get_page_permalink('shop') : home_url('/')); ?>">مشاهده محصول</a></article>
<article class="product"><div class="product-media"><span class="badge">محبوب</span><button class="heart" type="button" onclick="toggleHeart(this)" aria-label="افزودن Cloud Street به علاقه‌مندی‌ها">♡</button><div class="p-shoe" aria-hidden="true"><div class="p-upper"></div><div class="p-laces"></div><div class="p-sole"></div></div></div><div class="product-info"><h3>Cloud Street / Blue</h3><div class="meta"><span>کفش روزمره مردانه</span><span class="price">۳,۴۵۰,۰۰۰ تومان</span></div></div><a class="primary" style="display:block;text-align:center;width:100%;margin-top:12px" href="<?php echo esc_url(function_exists('wc_get_page_permalink') ? wc_get_page_permalink('shop') : home_url('/')); ?>">مشاهده محصول</a></article>
<article class="product"><div class="product-media"><button class="heart" type="button" onclick="toggleHeart(this)" aria-label="افزودن Terra Court به علاقه‌مندی‌ها">♡</button><div class="p-shoe" aria-hidden="true"><div class="p-upper"></div><div class="p-laces"></div><div class="p-sole"></div></div></div><div class="product-info"><h3>Terra Court / Sand</h3><div class="meta"><span>کفش اسپرت مردانه</span><span class="price">۳,۱۵۰,۰۰۰ تومان</span></div></div><a class="primary" style="display:block;text-align:center;width:100%;margin-top:12px" href="<?php echo esc_url(function_exists('wc_get_page_permalink') ? wc_get_page_permalink('shop') : home_url('/')); ?>">مشاهده محصول</a></article>
<article class="product"><div class="product-media"><span class="badge">Limited</span><button class="heart" type="button" onclick="toggleHeart(this)" aria-label="افزودن Form 01 به علاقه‌مندی‌ها">♡</button><div class="p-shoe" aria-hidden="true"><div class="p-upper"></div><div class="p-laces"></div><div class="p-sole"></div></div></div><div class="product-info"><h3>Form 01 / Cream</h3><div class="meta"><span>کفش لوکس مردانه</span><span class="price">۴,۹۹۰,۰۰۰ تومان</span></div></div><a class="primary" style="display:block;text-align:center;width:100%;margin-top:12px" href="<?php echo esc_url(function_exists('wc_get_page_permalink') ? wc_get_page_permalink('shop') : home_url('/')); ?>">مشاهده محصول</a></article>
</div></section>
<section class="banner reveal" id="new" aria-labelledby="new-title"><div><div class="eyebrow" style="color:#777">NEW COLLECTION / 2026</div><h2 id="new-title">Move different.</h2><p>کالکشن جدید کفش‌های مردانه با فرم‌های ساده‌تر، رنگ‌های کاربردی و طراحی مناسب برای استفاده روزمره و استایل شهری.</p><a class="primary" href="<?php echo esc_url(function_exists('wc_get_page_permalink') ? wc_get_page_permalink('shop') : home_url('/')); ?>">مشاهده کالکشن جدید</a></div></section>
<section class="section reveal" id="about" aria-labelledby="about-title"><div class="section-head"><div><div class="eyebrow">About SOLE</div><h2 id="about-title" class="section-title">طراحی ساده، انتخاب مطمئن.</h2></div></div><p class="section-sub about-copy">ما روی انتخاب مدل‌هایی تمرکز می‌کنیم که ظاهر امروزی را با استفاده روزانه ترکیب می‌کنند؛ از کفش روزمره و اسپرت تا مدل‌های رانینگ و لوکس. تجربه خرید باید روشن، ساده و قابل اعتماد باشد.</p><div class="stats"><div class="stat"><b>01</b><span>طراحی مینیمال و کاربردی</span></div><div class="stat"><b>02</b><span>انتخاب متنوع برای استفاده روزانه</span></div><div class="stat"><b>03</b><span>پشتیبانی پیش از خرید</span></div></div></section>
<section class="section seo-copy reveal" aria-labelledby="seo-title"><div><div class="eyebrow">راهنمای انتخاب</div><h2 id="seo-title" class="section-title">خرید کفش مردانه متناسب با سبک زندگی</h2></div><div class="seo-grid"><p>برای خرید کفش مردانه بهتر است ابتدا نوع استفاده را مشخص کنید. کفش روزمره برای استفاده طولانی و استایل شهری مناسب است، در حالی که مدل‌های رانینگ برای فعالیت و حرکت انتخاب می‌شوند. کفش‌های اسپرت نیز گزینه‌ای چندمنظوره برای ترکیب راحتی و ظاهر روز هستند.</p><p>در انتخاب کفش، علاوه بر ظاهر به فرم پا، کاربرد، متریال، وزن و راحتی توجه کنید. در فروشگاه SOLE تلاش شده مدل‌های مختلف با توضیحات روشن در دسترس باشند تا مقایسه و انتخاب آسان‌تر شود.</p></div></section>
</main>
<div class="drawer" id="drawer" onclick="if(event.target===this)closeCart()" aria-hidden="true"><aside class="panel"><div class="panel-head"><h2>سبد خرید</h2><button class="close" type="button" onclick="closeCart()" aria-label="بستن سبد خرید">×</button></div><div id="cartItems"><p style="color:#777;font-size:13px">برای افزودن محصول، آن را از فروشگاه انتخاب کنید.</p></div><div class="cart-total"><span>مجموع</span><span id="total">۰ تومان</span></div><a class="primary" style="display:block;text-align:center;width:100%" href="<?php echo esc_url(function_exists('wc_get_cart_url') ? wc_get_cart_url() : home_url('/')); ?>">مشاهده سبد خرید</a></aside></div>
<div class="toast" id="toast" role="status" aria-live="polite"></div>
<script>
let cart=[];const toast=document.getElementById('toast');function showToast(t){toast.textContent=t;toast.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>toast.classList.remove('show'),2600)}function openCart(){document.getElementById('drawer').classList.add('open');document.getElementById('drawer').setAttribute('aria-hidden','false')}function closeCart(){document.getElementById('drawer').classList.remove('open');document.getElementById('drawer').setAttribute('aria-hidden','true')}function toggleHeart(b){b.textContent=b.textContent==='♡'?'♥':'♡';b.style.color=b.textContent==='♥'?'#111':'';showToast(b.textContent==='♥'?'به علاقه‌مندی‌ها اضافه شد':'از علاقه‌مندی‌ها حذف شد')}const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(x=>io.observe(x));
</script>
<?php get_footer(); ?>
