<?php get_header(); ?>
<main id="home" class="shell">
<section class="hero reveal"><div class="grain"></div><div class="hero-copy"><div class="eyebrow">Autumn / Winter 2026</div><h1>کفشی برای<br>حرکت <em>بعدی</em></h1><p>طراحی مینیمال، فرم دقیق و راحتی واقعی. مجموعه‌ای از کفش‌های روزمره و استایل شهری که برای حرکت ساخته شده‌اند.</p><div class="hero-cta"><a class="primary" href="<?php echo esc_url(function_exists('wc_get_page_permalink') ? wc_get_page_permalink('shop') : home_url('/')); ?>">مشاهده محصولات ←</a><a class="secondary" href="#new">▶ معرفی کالکشن</a></div></div><div class="shoe-stage"><div class="orbit"></div><div class="floating-tag">NEW DROP · 01 / 06</div><div class="shoe"><svg viewBox="0 0 620 360" xmlns="http://www.w3.org/2000/svg" aria-label="کفش"><defs><linearGradient id="g" x1="0" x2="1"><stop stop-color="#262626"/><stop offset="1" stop-color="#555"/></linearGradient></defs><path d="M88 235 C135 217 175 177 218 112 C240 78 271 68 302 90 L371 149 C409 181 455 188 518 205 L575 222 C604 231 613 252 593 269 C573 285 536 293 493 294 L147 294 C92 294 55 278 61 259 C65 248 74 241 88 235Z" fill="url(#g)"/><path d="M213 113 C241 83 270 75 302 96 L368 151 C334 173 295 183 247 175 L184 160Z" fill="#777" opacity=".55"/><path d="M95 252 C207 268 395 260 586 242 C606 250 605 267 585 278 C559 291 528 295 493 295 L145 295 C91 295 58 279 63 260Z" fill="#f1f0ec"/><path d="M278 123 L350 184 M257 134 L331 193 M235 145 L308 202" stroke="#ddd" stroke-width="8" stroke-linecap="round" opacity=".7"/><circle cx="450" cy="235" r="13" fill="#222"/><path d="M460 236 L560 245" stroke="#111" stroke-width="5" opacity=".5"/></svg></div></div></section>
<div class="ticker"><div class="ticker-track">DESIGNED FOR EVERYDAY MOTION ✦ NEW SEASON ✦ PREMIUM MATERIALS ✦ COMFORT FIRST ✦ DESIGNED FOR EVERYDAY MOTION ✦ NEW SEASON ✦ PREMIUM MATERIALS ✦ COMFORT FIRST ✦</div></div>
<section id="collections" class="section reveal"><div class="section-head"><div><div class="eyebrow">Explore</div><h2 class="section-title">کالکشن‌ها</h2></div><div class="section-sub">انتخاب کن و وارد دنیای هر سبک شو ←</div></div><div class="categories"><a class="cat" href="<?php echo esc_url(function_exists('wc_get_page_permalink') ? wc_get_page_permalink('shop') : home_url('/')); ?>"><small>01</small><div class="mini-shoe"></div><strong>روزمره</strong></a><a class="cat" href="<?php echo esc_url(function_exists('wc_get_page_permalink') ? wc_get_page_permalink('shop') : home_url('/')); ?>"><small>02</small><div class="mini-shoe"></div><strong>رانینگ</strong></a><a class="cat" href="<?php echo esc_url(function_exists('wc_get_page_permalink') ? wc_get_page_permalink('shop') : home_url('/')); ?>"><small>03</small><div class="mini-shoe"></div><strong>اسپرت</strong></a><a class="cat" href="<?php echo esc_url(function_exists('wc_get_page_permalink') ? wc_get_page_permalink('shop') : home_url('/')); ?>"><small>04</small><div class="mini-shoe"></div><strong>لوکس</strong></a></div></section>
<section id="shop" class="section reveal"><div class="section-head"><div><div class="eyebrow">Selected products</div><h2 class="section-title">انتخاب سردبیر</h2></div><a class="secondary" href="<?php echo esc_url(function_exists('wc_get_page_permalink') ? wc_get_page_permalink('shop') : home_url('/')); ?>">همه محصولات ←</a></div><div class="products">
<article class="product"><div class="product-media"><span class="badge">جدید</span><button class="heart" onclick="toggleHeart(this)">♡</button><div class="p-shoe"><div class="p-upper"></div><div class="p-laces"></div><div class="p-sole"></div></div></div><div class="product-info"><h3>Mono Runner / Black</h3><div class="meta"><span>کفش رانینگ</span><span class="price">۳,۸۹۰,۰۰۰ تومان</span></div></div><a class="primary" style="display:block;text-align:center;width:100%;margin-top:12px" href="<?php echo esc_url(function_exists('wc_get_page_permalink') ? wc_get_page_permalink('shop') : home_url('/')); ?>">افزودن به سبد</a></article>
<article class="product"><div class="product-media"><span class="badge">محبوب</span><button class="heart" onclick="toggleHeart(this)">♡</button><div class="p-shoe"><div class="p-upper"></div><div class="p-laces"></div><div class="p-sole"></div></div></div><div class="product-info"><h3>Cloud Street / Blue</h3><div class="meta"><span>روزمره</span><span class="price">۳,۴۵۰,۰۰۰ تومان</span></div></div><a class="primary" style="display:block;text-align:center;width:100%;margin-top:12px" href="<?php echo esc_url(function_exists('wc_get_page_permalink') ? wc_get_page_permalink('shop') : home_url('/')); ?>">افزودن به سبد</a></article>
<article class="product"><div class="product-media"><button class="heart" onclick="toggleHeart(this)">♡</button><div class="p-shoe"><div class="p-upper"></div><div class="p-laces"></div><div class="p-sole"></div></div></div><div class="product-info"><h3>Terra Court / Sand</h3><div class="meta"><span>اسپرت</span><span class="price">۳,۱۵۰,۰۰۰ تومان</span></div></div><a class="primary" style="display:block;text-align:center;width:100%;margin-top:12px" href="<?php echo esc_url(function_exists('wc_get_page_permalink') ? wc_get_page_permalink('shop') : home_url('/')); ?>">افزودن به سبد</a></article>
<article class="product"><div class="product-media"><span class="badge">Limited</span><button class="heart" onclick="toggleHeart(this)">♡</button><div class="p-shoe"><div class="p-upper"></div><div class="p-laces"></div><div class="p-sole"></div></div></div><div class="product-info"><h3>Form 01 / Cream</h3><div class="meta"><span>لوکس</span><span class="price">۴,۹۹۰,۰۰۰ تومان</span></div></div><a class="primary" style="display:block;text-align:center;width:100%;margin-top:12px" href="<?php echo esc_url(function_exists('wc_get_page_permalink') ? wc_get_page_permalink('shop') : home_url('/')); ?>">افزودن به سبد</a></article>
</div></section>
<section class="banner reveal" id="new"><div><div class="eyebrow" style="color:#777">NEW SEASON / 2026</div><h2>Move different.</h2><p>کالکشن جدید با فرم‌های ساده‌تر، متریال بهتر و رنگ‌هایی که با هر استایلی هماهنگ می‌شوند.</p><a class="primary" href="<?php echo esc_url(function_exists('wc_get_page_permalink') ? wc_get_page_permalink('shop') : home_url('/')); ?>">مشاهده کالکشن</a></div></section>
<section class="section reveal" id="about"><div class="section-head"><div><div class="eyebrow">Why SOLE</div><h2 class="section-title">کمتر، اما بهتر.</h2></div></div><div class="stats"><div class="stat"><b>01</b><span>طراحی مینیمال و ماندگار</span></div><div class="stat"><b>24H</b><span>تست راحتی برای استفاده روزانه</span></div><div class="stat"><b>100%</b><span>تمرکز روی جزئیات و کیفیت</span></div></div></section>
</main>
<?php get_footer(); ?>